# Generated by Django 5.2.7 on 2025-10-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meds", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="description",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="medicine",
            name="category",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
